### ISSUE TITLE
Broken download link

### ISSUE THREAD

**Issue by jochenberger** [eclipse/org.eclipse.rcptt#25] opened 2023-08-31 14:09 UTC
The nightly runner download link on https://eclipse.dev/rcptt/download/ is broken, it points to http://download.eclipse.org/rcptt/nightly///runner/rcptt.runner--N.zip

**Comment by basilevs** [comment] 2023-09-06 18:05
Commented in https://gitlab.eclipse.org/eclipsefdn/it/websites/eclipse.org/-/issues/376

**Comment by basilevs** [comment] 2023-09-11 17:53
The issue is fixed on hosting side. The links are accurate again.

**Closed by basilevs** 2023-09-11 17:53 UTC
