### ISSUE TITLE
exec-process fails with: error 13 permission denied since 2.5.5-M2

### ISSUE THREAD

**Issue by Mailaender** [eclipse/org.eclipse.rcptt#73] opened 2024-04-24 10:55 UTC
To reproduce, run the following ECL script

    exec-process "date" | show-alert

which will work inside the IDE but fail in the runner:

     Cause: Cannot run program "date": error=13, permission denied

This does not happen when starting the test within the IDE. It also works fine with `rcptt.runner-2.5.5-M0` and `rcptt.runner-2.5.5-M1`.

**Comment by Mailaender** [comment] 2024-04-24 11:17
[Diff](https://gist.github.com/Mailaender/a607110ec92674bb204b5ad9e2b03533/revisions) of the runner logs. [Changes](https://github.com/eclipse/org.eclipse.rcptt/compare/03beee7e7942200461df181fb27cbdac7e3bbca2...572de5ede5633e0000985053ffb9c5ffd358f2b6) since M1.

**Comment by basilevs** [comment] 2024-04-27 08:33
What is the error? Steps to reproduce?

**Comment by Mailaender** [comment] 2024-04-27 08:57
New workspace does not help. It also happens in M3 and it only happens using the runner. I believe it is some configuration flag that gives Java more permissions, but I haven't found it yet.

**Comment by basilevs** [comment] 2024-04-27 09:02
Runner works fine on Linux and Windows in my projects (which start a lot of external processes), so this is not reproducible.
I'm closing this until we have more information to work on.

**Comment by basilevs** [comment] 2024-04-27 09:04
BTW, in the attached runner log I see a failure to discover AUT's JRE. This should be fixed in M3. Also, the log is terminated before the AUT has started. Are you sure you've attached the appropriate log?

**Comment by Mailaender** [comment] 2024-04-27 09:08
To reproduce, run the following ECL script

```
exec-process "date" | show-alert
```

which will work inside the IDE but fail in the runner:

> Cause: Cannot run program "date": error=13, permission denied

**Comment by Mailaender** [comment] 2024-04-27 09:12
I used your [runner.sh](https://www.eclipse.org/rcptt/documentation/userguide/runner/runner.sh) as a template:

```sh
#*******************************************************************************
# Copyright (c) Xored Inc.
#
# All rights reserved.
#
#
# Contributors:
# Matthias Mailänder, Lablicate GmbH
#*******************************************************************************/

#! /bin/sh

runnerPath=./rcptt.runner-2.5.5/eclipse
project=../../../
autPath=./openchrom.demo-1.0.x

testResults=$project/../results/demo/$tests
runnerWorkspace=$testResults/runner-workspace
autWorkspace=$testResults/aut-workspace-
autOut=$testResults/aut-out-
autArgs="-eclipse.password;$(pwd)/master"
javaVM=$JAVA_HOME
junitReport=$testResults/results.xml
htmlReport=$testResults/results.html

rm -rf $testResults
mkdir -p $testResults

java -jar $runnerPath/plugins/org.eclipse.equinox.launcher_*.jar \
     -application org.eclipse.rcptt.runner.headless \
     -data $runnerWorkspace \
     -aut $autPath \
     -autArgs ${autArgs} \
     -autWsPrefix $autWorkspace \
     -autConsolePrefix $autOut \
     -autVM $javaVM \
     -htmlReport $htmlReport \
     -junitReport $junitReport \
     -import $project \
     -tests StartDate.test
```

**Comment by basilevs** [comment] 2024-04-27 09:15
What is the Java version? Could you try to reproduce on Eclipse Platform as AUT?

**Comment by Mailaender** [comment] 2024-04-27 09:16
I use `/usr/lib/jvm/java-17-temurin` both as system and bundled with the application.

**Comment by Mailaender** [comment] 2024-04-27 09:22
It runs fine using https://www.eclipse.org/downloads/download.php?file=/technology/epp/downloads/release/2024-03/R/eclipse-java-2024-03-R-linux-gtk-x86_64.tar.gz&mirror_id=1285 as AUT.

**Comment by Mailaender** [comment] 2024-04-27 10:40
Skimming through the code I noticed this

https://github.com/eclipse/org.eclipse.rcptt/blob/b51d48801138eb299516faa49bc7faf4f0e3d495/launching/org.eclipse.rcptt.launching.ext/src/org/eclipse/rcptt/launching/ext/Q7ExternalLaunchDelegate.java#L606-L616

**Comment by basilevs** [comment] 2024-04-27 15:32
As in runner.log I see a symptom that was supposed to be fixed in M3, could you please attach M3 runner log, which reproduces the problem?

**Comment by Mailaender** [comment] 2024-04-27 15:49
Updated https://gist.github.com/Mailaender/a607110ec92674bb204b5ad9e2b03533#file-rcptt-log

> progress: Resolving null

looks fishy

**Comment by basilevs** [comment] 2024-05-03 10:34
I've downloaded [OpenChrom](https://www.openchrom.net/download) and failed to reproduce the problem as described.
I get permission denied errors in Runner (and not in AUT) due to invalid configuration of OpenChrom:

```
vasiligulevich@Vasilis-MacBook-Pro exec-process %  /private/tmp/Eclipse.app/Contents/Eclipse/features/net.openchrom.jre.macosx.cocoa.aarch64.feature_17.0.11/jre/jdk-17.0.11+9-jre/Contents/Home/bin/java 
zsh: permission denied: /private/tmp/Eclipse.app/Contents/Eclipse/features/net.openchrom.jre.macosx.cocoa.aarch64.feature_17.0.11/jre/jdk-17.0.11+9-jre/Contents/Home/bin/java
```
@Mailaender please fix your AUT and retry.

**Comment by basilevs** [comment] 2024-05-03 11:42
I've struggled on MacOS due to spurious errors caused by invalid detection of AUT's JVM, so fixed that in #75.

**Closed** 2024-05-03 12:15 UTC

**Comment by basilevs** [comment] 2024-05-06 00:52
@Mailaender have you managed to fix the problem?

**Comment by basilevs** [comment] 2024-05-07 08:20
Please update me once AUT has correct permissions for embedded JRE.

**Comment by Mailaender** [comment] 2024-05-07 10:42
Seems to be a problem with the `.dmg` repackaging.

**Comment by Mailaender** [comment] 2024-05-07 10:43
On Linux I see another long-standing RCPTT bug https://bugs.eclipse.org/bugs/show_bug.cgi?id=515501
> Unknown file system layout of Java VM from ini file

Not sure if that is related.

**Comment by basilevs** [comment] 2024-05-07 10:49
> On Linux I see another long-standing RCPTT bug https://bugs.eclipse.org/bugs/show_bug.cgi?id=515501
Try #75

**Comment by Mailaender** [comment] 2024-05-07 14:26
> Please update me once AUT has correct permissions for embedded JRE.

https://share.lablicate.com/index.php/s/A8pzgQHAfZa7gfK

**Comment by basilevs** [comment] 2024-05-07 15:55
> https://share.lablicate.com/index.php/s/A8pzgQHAfZa7gfK

Yep, still can't reproduce. Attaching a sample project and a runner startup script. The runner was downloaded from https://ci.eclipse.org/rcptt/job/Pull_requests/job/PR-75/2/artifact/runner/product/target/rcptt.runner-2.5.5-SNAPSHOT.zip
[exec-process.zip](https://github.com/eclipse/org.eclipse.rcptt/files/15238006/exec-process.zip)

The archive also includes runner's console output.

**Comment by Mailaender** [comment] 2024-05-08 21:35
Using https://www.eclipse.org/downloads/download.php?file=/rcptt/nightly/2.5.5/202405081020/runner/rcptt.runner-2.5.5-N202405081020.zip I can confirm that this issue is gone. The error message 

> Unknown file system layout of Java VM from ini file

is no longer displayed. I think you fixed it and I guess it was https://github.com/eclipse/org.eclipse.rcptt/pull/75.

**Comment by basilevs** [comment] 2024-05-09 08:06
I have no further ideas how to diagnose exec-process problem. Have you tried scripts from my archive above?

**Comment by Mailaender** [comment] 2024-05-09 09:09
You already fixed it in the latest nightly.
