### ISSUE TITLE
News for updates around java21 and Eclipse 2024-06

### ISSUE THREAD

**Issue by christelleburguera** [eclipse/org.eclipse.rcptt#82] opened 2024-05-30 15:08 UTC
Hello,

What are your plans around the updates to support java21 and Eclipse 2024-06 ?
thank you so much for your answer, @basilevs :)

Have a very nice day
Christelle

**Comment by basilevs** [comment] 2024-05-30 17:03
I think they are supported in RCPTT 2.5.5-M3. Please report otherwise.
Closing as duplicate of https://github.com/eclipse/org.eclipse.rcptt/issues/35

**Closed by basilevs** 2024-05-30 17:03 UTC

**Comment by christelleburguera** [comment] 2024-05-31 07:12
thank you, we'll try :)
have a good day

**Comment by basilevs** [comment] 2024-05-31 07:51
> I try to have news about your plans around 202**4**-06 and java21

Please report if 2024-06 and Java 21 are producing bugs in 2.5.5-M3. This is a duplicate, because the support has not reached released RCPTT. (RCPTT 2.5.4 does not support latest platforms)
